name: shiny_mikrob
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3
  - r-shiny
  - r-markdown
  - r-phyloseq
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-stringr
  - r-vegan
  - r-data.table
  - r-reshape2
  - r-plotly
  - r-scales
  - r-colorbrewer
  - r-rcolorbrewer
  - r-ade4
  - r-htmltools
  - r-jsonlite
  - r-rlang
  - r-renv